// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const CustomMark: typeof import("./components/blocks/CustomMark.svelte")["default"]
    const ProjectQuote: typeof import("./components/ProjectQuote.svelte")["default"]
    const ProjectSection: typeof import("./components/ProjectSection.svelte")["default"]
    const ProjectSidebar: typeof import("./components/ProjectSidebar.svelte")["default"]
    const ProjectTechStack: typeof import("./components/ProjectTechStack.svelte")["default"]
    const ProjectTitle: typeof import("./components/ProjectTitle.svelte")["default"]
    const SvelteSeo: typeof import("svelte-seo")["default"]
}

export {}
